###
# ZSH Configuration

## Shell configuration:

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


###
# OH-MY-ZSH Configuration:

# Path to your oh-my-zsh installation:
export ZSH=$HOME/.oh-my-zsh

# Theme:
ZSH_THEME="robbyrussell"

# Plugins:
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh


###
# User configuration

# Variables:
export EDITOR='vim'

# Specific configurations:
[ -f ~/.tis/suite/shell/init.zsh ] && source ~/.tis/suite/shell/init.zsh
[ -f ~/.taas/suite/shell/init.zsh ] && source ~/.taas/suite/shell/init.zsh

if type tis-config > /dev/null 2>&1; then
    PATH=$(tis-config get prefix)/opam/bin:$PATH
    PATH="$(tis-config get prefix)/llvm/bin:$PATH"
    PATH="$(tis-config get prefix)/creduce/bin:$PATH"

    export OPAMROOT=$(tis-config get prefix)/opam/root
    . $(tis-config get prefix)/opam/root/opam-init/init.sh > /dev/null 2>&1 || true
fi
eval $(opam config env)

# Python configuration:
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv > /dev/null 2>&1; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
