#!/usr/bin/env bash

# Setup background
feh --bg-fill \
    ~/.xmonad/resources/wallpaper-1.jpg \
    ~/.xmonad/resources/wallpaper-2.jpg \
    ~/.xmonad/resources/wallpaper-3.jpg &

# Start xscreensaver
sleep 3 && xscreensaver -no-splash &



###########
# ICON TRAY

setup_tray() {

    # Setup the tray
    stalonetray &

    # Wait the tray to be ready
    sleep 3

    # Start nm-applet if it exists
    ( type nm-applet > /dev/null && nm-applet --sm-disable ) &
}

# Comment: the stalone tray is disable for now, since it is not necessary as
# is for the moment.
# setup_tray
