
- name: Setup the environment
  hosts: local
  roles:

    # Git must be install first.
    - role: git
      tags:
        - git

    # Initialize the apt repository
    # - role: init
    #   tags:
    #     - init

    - role: zsh
      tags:
        - zsh

    # Initialize xmonad
    - role: xmonad
      tags:
        - xmonad

    - role: python
      tags:
        - python

    - role: aws
      tags:
        - aws

    # Initialize tmux
    - role: tmux
      tags:
        - tmux
