
- name: Setup the environment
  hosts: local
  roles:

    # Git must be install first.
    - role: git
      tags:
        - git

    # Initialize the apt repository
    # - role: init
    #   tags:
    #     - init

    - role: packages
      tags:
        - packages

    - role: zsh
      tags:
        - zsh

    - role: konsole
      tags:
        - konsole

    - role: xmonad
      tags:
        - xmonad

    - role: python
      tags:
        - python

    - role: aws
      tags:
        - aws

    - role: shellcheck
      tags:
        - shellcheck

    - role: docker
      tags:
        - docker

    # Initialize tmux
    - role: tmux
      tags:
        - tmux
