
- name: Install generic apt packages
  apt:
    name: "{{ apt_packages }}"
  become: true
  become_method: sudo
  vars:
    apt_packages:
      - gksu
      - gmrun
      - shellcheck
      - stalonetray             # For: nm-applet
      - suckless-tools          # For: dmenu
      - xcompmgr
      - xscreensaver
      - xscreensaver-gl

