
- name: Install xmonad and xmobar with core and contrib functionality using apt-get
  apt:
    name: "{{ xmonad_packages }}"
  become: true
  become_method: sudo
  vars:
    xmonad_packages:
      - xmobar
      - xmonad
      - libghc-xmonad-dev
      - libghc-xmonad-contrib-dev

- name: Create xmonad configuration directory
  file:
    path: "{{ user_home }}/.xmonad"
    state: directory

- name: Link the XMonad configuration file
  file:
    src: "{{ role_path }}/files/xmonad.hs"
    dest: "{{ user_home }}/.xmonad/xmonad.hs"
    state: link

- name: Link the XMobar configuration file
  file:
    src: "{{ role_path }}/files/xmobarrc"
    dest: "{{ user_home }}/.xmobarrc"
    state: link

- name: Link the Xmonad-session configuration file
  file:
    src: "{{ role_path }}/files/xmonad-session-rc"
    dest: "{{ user_home }}/.xmonad/xmonad-session-rc"
    state: link

- name: Link the binary folder
  file:
    src: "{{ role_path }}/files/binaries"
    dest: "{{ user_home }}/.xmonad/binaries"
    state: link

- name: Link the stalonetray configuration file
  file:
    src: "{{ role_path }}/files/stalonetrayrc"
    dest: "{{ user_home }}/.stalonetrayrc"
    state: link


# Setup xscreensaver

- name: Link the xscreensaver
  file:
    src: "{{ role_path }}/files/xscreensaver"
    dest: "{{ user_home }}/.xscreensaver"
    state: link

- name: Delete gnome-screensaver
  apt:
    name: gnome-screensaver
    state: absent
  become: true
  become_method: sudo

- name: Link the binary
  file:
    src: /usr/bin/xscreensaver-command
    dest: /usr/bin/gnome-screensaver-command
    state: link
  become: true
  become_method: sudo

- name: Create the directory ~/.config/xscreensaver/
  file:
    path: "{{ user_home }}/.config/xscreensaver"
    recursive: yes
    state: directory
